// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnpudutmocqufcayneai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJucHVkdXRtb2NxdWZjYXluZWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNjExOTUsImV4cCI6MjA4NDczNzE5NX0.17jBXfPMxmL13xEwLYN2FxSN_g6x4OSqURIsPs0xoF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});